### ISSUE TITLE
'#' character is missing from the map for the Haritha font

### ISSUE THREAD

**Issue by alenpaulvarghese** [libindic/unicode-conversion-maps#1]
```py
Cell In[11], line 1
----> 1 maps['Haritha']['#']

KeyError: '#'
```

The clean function is removing the entry treating it as a comment.

**Comment by asdofindia** [comment]
This is inherited from payyans, I think

https://github.com/libindic/payyans/blob/908e8a943845f815fbbf9a1e966782c03d353ffe/libindic/payyans/core.py#L202

If so, it must be a long standing bug ha ha. Thanks for uncovering it.

I really think the comments should be removed from map file and the attribution details moved to the readme of this repo. This will simplify matters. 

What do you think?

**Comment by alenpaulvarghese** [comment]
I think that would be better. 

Will the readme be a single file within the maps folder with a heading as the font name and its attribute and licence as paragraphs?

**Comment by asdofindia** [comment]
I'm thinking the main README of the repo itself.

Yeah, separately putting each font means that also becomes documentation of what fonts are available.

**Comment by asdofindia** [comment]
I don't think we need license for each font. We can have one license at the end for the whole repo.

**Comment by alenpaulvarghese** [comment]
If that' the case, we can add the contributors name in the main readme section.

**Comment by subins2000** [comment]
Instead of changing the comment syntax, to distinguish between comments and actual rule line, how about making the condition of a rule line like this:

> it is a rule line if if "=" present in the line and line.runes.length < 5

**Comment by asdofindia** [comment]
> line.runes.length < 5

```
Ì=സ്റ്റ
```

in https://github.com/libindic/unicode-conversion-maps/blob/12c20fee33edddebe614c4d96aa0797f4c6dbead/maps/ML-TTAmbili.map#L116 needs 7 runes I think.

I suggest keeping this at 10
